import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Button from "../components/button";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-full p-[16px] flex flex-col gap-y-[36px]'>
        <div className='w-full flex flex-col justify-center items-center gap-y-[4px] text-white'>
          <p className='text-[36px] font-bold'>TO DO LIST</p>
          <p className='font-medium text-[18px]'>Create a list of tasks :</p>
        </div>

          <div>
              <Button>test</Button>
          </div>
      </main>
    </div>
  )
}

export default Home
